services:
  - type: web
    name: smart-feedback-client
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NIXPACKS_YARN
        value: false
